DjangoProject/DjangoApp/urls.py
from django.urls import path
from .import views

app_name = "MyApp"

urlpatterns =[
    path('',views.export_csv, name='export_csv')

]





DjangoProject/DjangoProject/urls.py
from django.urls import path, include



urlpatterns = [
    #path('admin/', admin.site.urls),
    path('export_csv/', include("MyApp.urls", namespace="export_csv")),
    path('', include('MyApp.urls')),
    
    
]

DjangoProject/DjangoApp/models.py

from django.db import models

# Create your models here.
class Student(models.Model):
    FirstName = models.CharField("Enter First Name", max_length=50)
    LastName = models.CharField("Enter Last Name", max_length=50)
    City = models.CharField("Enter City", max_length=50)





DjangoProject/DjangoApp/forms.py
from django import forms

    

DjangoProject/DjangoApp/views.py
# Create your views here.
from django.shortcuts import render
import csv
import sqlite3
from django.http import HttpResponse
from .models import Student

def export_csv(request):
    template_name = 'Posts/main.html'
    # Create a CSV response object
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="exportDataset.csv"'

    students = Student.objects.all()

    # Create a CSV writer object
    writer = csv.writer(response)

    # Write the header row
    writer.writerow(['FirstName', 'LastName', 'City'])

    # Write the data rows
    for row in students:
        writer.writerow(row)

    return response
   




DjangoProject/DjangoApp/templates/Posts/main.html

<style>
    button {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 15px 32px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      cursor: pointer;
    }
  </style>

<div class="model fade" id="download-model" tabindex="1">
    <div class="model-dialog">
        <div class="model-content">
            <div class="model-header">
                <h3 class="model-title"> Download Data</h3>
                <button type="button" class="btn-close" data-bs-dismiss="model" aria-label="close"> 

                </button>
            </div>
            <div class="model-body">
                <form action="{% url 'MyApp:export_csv' %}" method="post">
                    {% csrf_token %}
                    
                    <button type="submit" class="btn-btn-primary">
                        
                         Download 
                        
                    </button>
                </form>
            </div>
        </div>

    </div>

</div>


